services:
  - type: web
    name: DATOM
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn datom.wsgi"
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: datom.settings
