# Generated by Django 5.0.6 on 2025-03-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_proyecto_id_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
