# Generated by Django 5.0.6 on 2025-03-23 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_proyecto_nombre_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pieza', models.CharField(max_length=100)),
                ('tipoDe_defecto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('nombre_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='core.proyecto')),
            ],
            options={
                'db_table': 'SCRAP_montaje',
                'permissions': [('puede_detallar_scrap', 'Puede detallar Scrap'), ('puede_editar_scrap', 'Puede editar Scrap'), ('puede_listar_scrap', 'Puede listar Scrap'), ('puede_eiminar_scrap', 'Puede eliminar Scrap'), ('puede_crear_scrap', 'Puede crear Scrap')],
                'indexes': [models.Index(fields=['nombre_proyecto'], name='SCRAP_monta_nombre__b9015a_idx'), models.Index(fields=['nombre_pieza'], name='SCRAP_monta_nombre__42e608_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scrap',
            constraint=models.UniqueConstraint(fields=('nombre_proyecto', 'nombre_pieza'), name='unique_scrap'),
        ),
    ]
